### ISSUE TITLE
[Request] This mod for Quest?

### ISSUE THREAD

**Issue by phazei** [ErisApps/SongChartVisualizer#10]
Someone made one a long while ago here:
https://github.com/henwill8/SongDifficultyChart

It's no longer working with v1.25.1, last worked with v1.17.1

I'm not sure how different the mod architecture is for modding pc vs quest, but I was hoping if you had the time, you might be able to make a quest version?

thanks

**Comment by ErisApps** [comment]
I'm sorry but the only thing that the PC and Quest versions share in common, is what they try to achieve.
The modding architecture is like day and night, and right... it's not possible to share even a single line of code. The programming languages are not even the same, C# is used for PCVR mods while C++ (and for rarer cases Rust) has to be used for Quest mods.

So no, can't help with that.
