### ISSUE TITLE
SCV preventing Chroma maps from working on 1.25.1

### ISSUE THREAD

**Issue by Fatalution** [ErisApps/SongChartVisualizer#9]
Whilst working on my WIP Chroma map, I've run into an issue with SCV. I am unsure if that is limited to WIP maps.
Because of SCV bugging out for some reason, the Chroma events just stop working, whilst the log is literally spammed with SCV errors.

Attaching video: https://streamable.com/7obcjl
Attaching log: [latest_SCV_Chroma_bug.log](https://github.com/ErisApps/SongChartVisualizer/files/9836073/latest_SCV_Chroma_bug.log)

**Comment by ErisApps** [comment]
Will look into it.

**Comment by ErisApps** [comment]
Resolved as of 1.1.8, will be released as soon as I can fix the build agent issue.
